#!/usr/bin/env python3
"""Generate compact 4-bit bitmap fonts for the Chromatic Deck renderer."""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "firmware" / "assets" / "fonts"
OUTPUT_HPP = ROOT / "firmware" / "src" / "display" / "font_deck.hpp"
OUTPUT_CPP = ROOT / "firmware" / "src" / "display" / "font_deck.cpp"
FIRST_CHARACTER = 0x20
LAST_CHARACTER = 0x7E

FONTS = [
    ("Switch", ASSETS / "BarlowCondensed-SemiBold.ttf", 48),
    ("Title", ASSETS / "BarlowCondensed-SemiBold.ttf", 36),
    ("CompactTitle", ASSETS / "BarlowCondensed-SemiBold.ttf", 28),
    ("Bank", ASSETS / "BarlowCondensed-SemiBold.ttf", 24),
    ("Label", ASSETS / "AtkinsonHyperlegible-Bold.otf", 13),
    ("Footer", ASSETS / "AtkinsonHyperlegible-Bold.otf", 16),
]


def generate_font(path: Path, size: int):
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    glyphs = []
    pixels = []
    for codepoint in range(FIRST_CHARACTER, LAST_CHARACTER + 1):
        character = chr(codepoint)
        left, top, right, bottom = font.getbbox(character)
        width = max(0, right - left)
        height = max(0, bottom - top)
        advance = max(1, round(font.getlength(character)))
        offset = len(pixels)
        alpha_values = []
        if width and height:
            image = Image.new("L", (width, height), 0)
            ImageDraw.Draw(image).text((-left, -top), character, font=font, fill=255)
            alpha_values = [min(15, (value + 8) // 17) for value in image.get_flattened_data()]
        for index in range(0, len(alpha_values), 2):
            high = alpha_values[index]
            low = alpha_values[index + 1] if index + 1 < len(alpha_values) else 0
            pixels.append((high << 4) | low)
        glyphs.append((offset, width, height, left, top, advance))
    return ascent + descent, glyphs, pixels


def format_values(values, per_line=16, formatter=lambda value: str(value)):
    lines = []
    for index in range(0, len(values), per_line):
        lines.append("    " + ", ".join(formatter(value) for value in values[index:index + per_line]))
    return ",\n".join(lines)


def main():
    generated = []
    for name, path, size in FONTS:
        line_height, glyphs, pixels = generate_font(path, size)
        generated.append((name, line_height, glyphs, pixels))

    OUTPUT_HPP.write_text("""#pragma once

#include <cstdint>
#include <span>

namespace midi::display {

enum class DeckFontRole : std::uint8_t {
  Switch,
  Title,
  CompactTitle,
  Bank,
  Label,
  Footer,
};

struct DeckGlyph {
  std::uint32_t offset{};
  std::uint16_t width{};
  std::uint16_t height{};
  std::int8_t bearingX{};
  std::int8_t bearingY{};
  std::uint8_t advance{};
};

struct DeckFont {
  std::span<const DeckGlyph> glyphs;
  std::span<const std::uint8_t> pixels;
  std::uint8_t firstCharacter{};
  std::uint8_t lastCharacter{};
  std::uint8_t lineHeight{};
};

const DeckFont& deck_font(DeckFontRole role);

}  // namespace midi::display
""")

    sections = ["""// Generated by firmware/tools/generate_display_fonts.py. Do not edit by hand.
#include \"font_deck.hpp\"

#include <array>

namespace midi::display {
namespace {
"""]
    for name, line_height, glyphs, pixels in generated:
        glyph_values = [
            "{" + ", ".join(str(value) for value in glyph) + "}" for glyph in glyphs
        ]
        sections.append(
            f"constexpr std::array<DeckGlyph, {len(glyphs)}> k{name}Glyphs{{{{\n"
            + format_values(glyph_values, 2, lambda value: value)
            + "\n}};\n"
        )
        sections.append(
            f"constexpr std::array<std::uint8_t, {len(pixels)}> k{name}Pixels{{{{\n"
            + format_values(pixels, 20, lambda value: f"0x{value:02X}")
            + "\n}};\n"
        )
        sections.append(
            f"const DeckFont k{name}Font{{k{name}Glyphs, k{name}Pixels, "
            f"{FIRST_CHARACTER}, {LAST_CHARACTER}, {line_height}}};\n"
        )
    sections.append("""
}  // namespace

const DeckFont& deck_font(DeckFontRole role) {
  switch (role) {
    case DeckFontRole::Switch: return kSwitchFont;
    case DeckFontRole::Title: return kTitleFont;
    case DeckFontRole::CompactTitle: return kCompactTitleFont;
    case DeckFontRole::Bank: return kBankFont;
    case DeckFontRole::Label: return kLabelFont;
    case DeckFontRole::Footer: return kFooterFont;
  }
  return kLabelFont;
}

}  // namespace midi::display
""")
    OUTPUT_CPP.write_text("\n".join(sections))

    total_bytes = sum(len(pixels) for _, _, _, pixels in generated)
    print(f"Generated {len(generated)} font sizes using {total_bytes} packed bitmap bytes")


if __name__ == "__main__":
    main()
